name: Sync Manual to Google Drive

on:
  push:
    branches: [ main ]
    paths:
      - '**/*manual-update*.md'
  workflow_dispatch:  # 手動実行オプション

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
           
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client oauth2client
          
      - name: List files
        run: find . -name "*manual-update*.md"
          
      - name: Upload to Google Drive
        env:
          GOOGLE_DRIVE_CREDENTIALS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
        run: python .github/scripts/upload_to_drive.py
